name: html_tidy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  html_tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install tidy

      - name: Check all HTML files
        run: |
          tidy -config tidy.config *.html
